
type_config = {
    'debug': {'dtype': bool, 'opt': False, 'doc': 'Toggle verbose debug logs.', 'requires': None},
    'ext': {'dtype': list, 'opt': False, 'doc': 'Extension to save to', 'requires': None},
    'outputfname': {'dtype': str, 'opt': False, 'doc': 'Output file name', 'requires': None},
    'imagecenterra': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'imagecenterdec': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'imagewidthra': {'dtype': float, 'opt': False, 'doc': '', 'requires': None},
    'imagewidthdec': {'dtype': float, 'opt': False, 'doc': '', 'requires': None},
    'distance': {'dtype': float, 'opt': False, 'doc': 'distance to source pc', 'requires': None},
    'backgroundfile': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'backgroundplotcolor': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'backgroundplotvmin': {'dtype': int, 'opt': False, 'doc': '', 'requires': 'backgroundplotcolor'},
    'backgroundplotvmax': {'dtype': int, 'opt': False, 'doc': '', 'requires': 'backgroundplotcolor'},
    'backgroundplotrms': {'dtype': float, 'opt': False, 'doc': '', 'requires': 'backgroundplotcolor'},
    'backgroundcontourmanual': {'dtype': list, 'opt': False, 'doc': '', 'requires': 'backgroundplotcolor'},
    'backgroundnegcontour': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontour': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourcolor': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourstart': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourint': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourend': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourrms': {'dtype': float, 'opt': False, 'doc': '', 'requires': None},
    'contourlinesize': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'backgroundcontourlvlfmt': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'colormap': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'colormapinvert': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'fluxstretch': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'titlecolor': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'textcolor': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'titlesize': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'textsize': {'dtype': int, 'opt': False, 'doc': '', 'requires': None},
    'beampad': {'dtype': float, 'opt': False, 'doc': '', 'requires': None},
    'showbeam': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'showcolorbar': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'showscalebar': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'scalebarlength': {'dtype': float, 'opt': False, 'doc': '', 'requires': 'showscalebar'},
    'scalebarunit': {'dtype': str, 'opt': False, 'doc': '', 'requires': 'scalebarlength'},
    'showlegend': {'dtype': bool, 'opt': False, 'doc': '', 'requires': 'showscalebar'},
    'legendlocation': {'dtype': int, 'opt': False, 'doc': '', 'requires': 'showlegend'},
    'figuresize': {'dtype': list, 'opt': False, 'doc': '', 'requires': None},
    'titles': {'dtype': list, 'opt': False, 'doc': '', 'requires': None},
    'showAxisLabels': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'xaxislabel': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'yaxislabel': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'coloraxislabel': {'dtype': str, 'opt': False, 'doc': '', 'requires': None},
    'showcontourlabels': {'dtype': bool, 'opt': False, 'doc': '', 'requires': None},
    'moleculeX_file': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_rms': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_start': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_int': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_end': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_plotcolor': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_plotcolorcmap': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_contourmanual': {'dtype': list, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redfile': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redname': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redrms': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redstart': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redint': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redend': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redcontourcolor': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redneg': {'dtype': bool, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_redcontourmanual': {'dtype': list, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluefile': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluename': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluerms': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluestart': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_blueint': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_blueend': {'dtype': int, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluecontourcolor': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_blueneg': {'dtype': bool, 'opt': True, 'doc': '', 'requires': None},
    'moleculeX_bluecontourmanual': {'dtype': list, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_ra': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_dec': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_redlength': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_redangle': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_bluelength': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'outflowX_blueangle': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'markerX_name': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'markerX_ra': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'markerX_dec': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'markerX_style': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
    'markerX_width': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'markerX_height': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'markerX_angle': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'markerX_size': {'dtype': float, 'opt': True, 'doc': '', 'requires': None},
    'markerX_display': {'dtype': float, 'opt': True, 'doc': 'Distance from marker center in arcsec along ra', 'requires': None},
    'markerX_color': {'dtype': str, 'opt': True, 'doc': '', 'requires': None},
}

default_config = {
    'debug': False,
    'ext': ['pdf'],
    'outputfname': '',
    'imagecenterra': '',
    'imagecenterdec': '',
    'imagewidthra': 10.,
    'imagewidthdec': 10.,
    'distance': 300.,  # distance to source in pc
    'backgroundfile': '',
    'backgroundcontourmanual': [],
    'backgroundnegcontour': False,
    'backgroundplotcolor': True,
    'backgroundplotvmin': 10,
    'backgroundplotvmax': 300,
    'backgroundplotrms': 8e-4,
    'backgroundcontour': True,
    'backgroundcontourcolor': 'black',
    'backgroundcontourstart': 3,
    'backgroundcontourint': 1,
    'backgroundcontourend': 30,
    'backgroundcontourrms': 1e-5,
    'contourlinesize': 2,
    'backgroundcontourlvlfmt': r'%s km $s^{-1}$',
    'figuresize': [10, 10],
    'colormap': 'ds9bb',
    'colormapinvert': False,
    'fluxstretch': 'sqrt',
    'titlecolor': 'black',
    'textcolor': 'black',
    'titlesize': 15,
    'textsize': 10,
    'beampad': 30.,
    'showbeam': True,
    'showAxisLabels': True,
    'showcolorbar': True,
    'showscalebar': True,
    'scalebarlength': 1,
    'scalebarunit': 'arcsec',
    'showlegend': True,
    'legendlocation': 0,
    'titles': ['Scientific Image'],
    'xaxislabel': 'RA (J2000)',
    'yaxislabel': 'DEC (J2000)',
    'coloraxislabel': 'Flux Density (Jy beam$^{-1}$)',
    'showcontourlabels': True,
    'moleculeX_file': '',
    'moleculeX_rms': -1.,
    'moleculeX_start': -1,
    'moleculeX_int': -1,
    'moleculeX_end': -1,
    'moleculeX_plotcolor': False,
    'moleculeX_plotcolorcmap': '',
    'moleculeX_contourmanual': [],
    'moleculeX_redfile': '',
    'moleculeX_redname': '',
    'moleculeX_redrms': -1.,
    'moleculeX_redstart': -1,
    'moleculeX_redint': -1,
    'moleculeX_redend': -1,
    'moleculeX_redcontourcolor': '',
    'moleculeX_redneg': False,
    'moleculeX_redcontourmanual': [],
    'moleculeX_bluefile': '',
    'moleculeX_bluename': '',
    'moleculeX_bluerms': -1.,
    'moleculeX_bluestart': -1,
    'moleculeX_blueint': -1,
    'moleculeX_blueend': -1,
    'moleculeX_bluecontourcolor': '',
    'moleculeX_blueneg': False,
    'moleculeX_bluecontourmanual': [],
    'outflowX_ra': None,
    'outflowX_dec': None,
    'outflowX_redlength': None,
    'outflowX_redangle': None,
    'outflowX_bluelength': None,
    'outflowX_blueangle': None,
    'markerX_name': '',
    'markerX_ra': '',
    'markerX_dec': '',
    'markerX_style': '',
    'markerX_width': -1.,
    'markerX_height': -1.,
    'markerX_angle': -1.,
    'markerX_size': -1.,
    'markerX_display': -1,
    'markerX_color': 'black',
}

default = {}
for k in type_config:
    default[k] = {**type_config[k], **{'default': default_config[k]}}
