"""nkrpy.
Originally was just a collection of python programs that I 

    found myself using repeatidly. Migrating a lot of more

    efficient modules and made more general.



If you would like to run the development version, please pull

    from the github instead as the pypi distribution excludes

    the docs, tests, and other potentially useful things.


======================================
This file is autogenerated by setup.py
======================================
"""
# flake8: noqa
from .misc import *
from . import misc
from .io import *
from . import io
Log = io.Log
from . import _types as types
from ._types import *
from ._unit import Unit
from . import _math as math
from . import _help
from ._help import *
__all__ = ['Unit', 'Log'] +\
                types.__all__ +\
                misc.__all__ +\
                _help.__all__+\
                io.__all__ +\
                ['math']


PACKAGES = __all__.copy()
PACKAGES.sort()

# end of init-generator template
