"""nkrpy.


Originally was just a collection of python programs that I 

    found myself using repeatidly. Migrating a lot of more

    efficient modules and made more general.


======================================
This file is autogenerated by setup.py
======================================
"""
# flake8: noqa
from .astro import dustmodels
from . import math
from .unit import Unit, convert
from . import publication
from .misc import (colours, constants, decorators, errors, mp,
                   typecheck, addspace, between,
                   find_nearest, strip, get, list_comp,
                   add, find_max)

__all__ = ('dustmodels',
           'math',
           'Unit', 'convert',
           'publication',
           'colours', 'constants', 'decorators', 'errors', 'mp',
           'typecheck', 'addspace', 'between',
           'find_nearest', 'strip', 'get', 'list_comp',
           'add', 'find_max')
